### ISSUE TITLE
What's the future of this package?

### ISSUE THREAD

**Issue by nth-commit** [mauricedb/polly-js#141]
Hey @mauricedb,

First of all, big ups for maintaining this package for so long and responding to the trickle of issues of many years.

I just wanted to direct your attention quickly to this package: https://github.com/connor4312/cockatiel (in case you were not aware of it). It contains a much more complete port of Polly (it has bulkhead, circuit breakers, timeouts), and is still being actively developed.

The existence of polly-js makes cockatiel really hard to find when googling for "javascript polly .net" - or something similar. The name polly-js totally dominates that search space.

Do you have plans to reach feature parity with Polly .NET? If not, would you consider linking cockatiel in polly-js's readme?

Thanks 🙂

**Comment by mauricedb** [comment]
Hi Michael,

Thanks for pointing Cockatiel out, I was not aware of it. Looks like a useful package. Are you a contributor?

I am not planning on adding a new features to Polly-js at the moment. Too busy with other things and the  `polly().waitAndRetry()` is pretty much what I need. So I prefer to keep it small and focused. That said, if someone opens a PR with new functionality I would merge it in.

Looks like Cockatiel is doing fine to me based on the number of stars and download statistics [here](https://www.npmtrends.com/polly-js-vs-cockatiel). But I have no objections to cross linking to it as long as it goes both ways.

Thanks,
Maurice

**Comment by nth-commit** [comment]
Yo 😄 

No, I'm not a maintainer of cockatiel, just a heavy user of Polly .NET that was searching for a JS port that had bulkhead/circuit breaker mechanisms.

I mean, I can try broker a deal if it helps others in my (possibly rare) situation find what they're looking for.

Cheers 👍

**Comment by mauricedb** [comment]
Sound like you would have been helped more my a note in the. NET version of Polly.

You can always open a PR there.

Thanks
Maurice
