### ISSUE TITLE
Plans for Circuit breaker, BulkHead etc

### ISSUE THREAD

**Issue by sandipray63in** [mauricedb/polly-js#75]
Hi,
Are there any plans for incorporating Circuit Breaker, Timeout, Bulkhead Isolation patterns(alongwith PolicyWrap) just like done in the orginal Polly.NET framework?

Regards,
Sandip

**Comment by mauricedb** [comment]
Hi @sandipray63in,

I don't have any current plans or time to do so myself.

I am fine with accepting pull requests though.

Regards,
Maurice
