### ISSUE TITLE
Is there way to get current attempt number when a retry happens?

### ISSUE THREAD

**Issue by ghaisassujit** [mauricedb/polly-js#92]
Scenario below:

polly().handle((err) => {
            // TODO: Log error.
           // TODO: Log Retry Attempt number and make some decision based on it.
            return true;
        })
            .waitAndRetry([60000, 1800000, 3600000])
            .executeForPromise(() => {return this.doDownload();})

**Comment by mauricedb** [comment]
Hi, I can see that would be useful. Right now only the error is provided as the `handle()` is meant for deciding what errors to retry and which ones not.

I wil be happy to include a PR that adds it as a second parameter object just like is done with some other functions.

**Comment by carmo-evan** [comment]
My workaround:

```javascript
let retries = 0;
polly().handle((err) => {
    // TODO: Log error.
    // TODO: Log Retry Attempt number and make some decision based on it.
    retries++;
    if (retries > 3) {
       // do something
    }
    return true;
})
.waitAndRetry([60000, 1800000, 3600000])
.executeForPromise(() => {return this.doDownload();})
```

**Comment by mauricedb** [comment]
@carmo-evan 

Is the `retries` counter being reset before a request or after a sucesfull completion?
